### ISSUE TITLE
It is possible it install ads-b project this dump1090 for dump1090-fa

### ISSUE THREAD

**Issue by lordkane** [Mictronics/dump1090#11]
It is possible it install ads-b project this dump1090 for dump1090-fa

i have problems to install it 
the libiio and the other lib..... make me problems...

sorry for my bad english

Greetings 
Michael near Dortmund

**Comment by Mictronics** [comment]
@lordkane Dann probiers mal auf Deutsch.

**Comment by lordkane** [comment]
ich es möglich das dump1090 Mictronics wenn auf dem ads-b project dump1090-fa installiert ist.
das zu installiert drüber ... hatte im make file blazesdr und noch eins aus gemacht das nur rtlsdr und agessive an hatte hatte ich problem beim installieren wollte diese libiio und dieses andere libioo mit der nummer auch haben ..

hätte gerne mein ads-b project mit deinem dump1090 Mictronics gerne laufen

gruss Micha aus der nähe von Dortmund

**Comment by Mictronics** [comment]
`make -f Makefile all HTMLPATH=/usr/share/dump1090-fa/html BLADERF=no RTLSDR=yes AGGRESSIVE=yes PLUTOSDR=no HAVE_BIASTEE=no` (Für den dev Branch)
Damit wird nur für RTLSDR kompiliert. Die libiio und libad9361 sind dafür nicht nötig.
Mit `sudo cp dump1090 /usr/bin/dump1090-fa` kannst du die originale Binary überschreiben. Vorher den Service stoppen.

**Comment by lordkane** [comment]
ake -f Makefile all HTMLPATH=/usr/share/dump1090-fa/html BLADERF=no RTLSDR=yes AGGRESSIVE=yes PLUTOSDR=no HAVE_BIASTEE=no
cc -g -o dump1090 dump1090.o anet.o interactive.o mode_ac.o mode_s.o comm_b.o net_io.o crc.o demod_2400.o stats.o cpr.o icao_filter.o track.o util.o convert.o sdr_ifile.o sdr_beast.o sdr.o sdr_rtlsdr.o -L/usr/local/lib -lpthread -lm -lrt -lrtlsdr -lusb-1.0 -lncurses
sdr.o:(.data.rel+0x20): undefined reference to `bladeRFInitConfig'
sdr.o:(.data.rel+0x24): undefined reference to `bladeRFHandleOption'
sdr.o:(.data.rel+0x28): undefined reference to `bladeRFOpen'
sdr.o:(.data.rel+0x2c): undefined reference to `bladeRFRun'
sdr.o:(.data.rel+0x30): undefined reference to `bladeRFClose'
sdr.o:(.data.rel+0x40): undefined reference to `plutosdrInitConfig'
sdr.o:(.data.rel+0x44): undefined reference to `plutosdrHandleOption'
sdr.o:(.data.rel+0x48): undefined reference to `plutosdrOpen'
sdr.o:(.data.rel+0x4c): undefined reference to `plutosdrRun'
sdr.o:(.data.rel+0x50): undefined reference to `plutosdrClose'
collect2: error: ld returned 1 exit status
Makefile:58: die Regel für Ziel „dump1090“ scheiterte
make: *** [dump1090] Fehler 1

**Comment by lordkane** [comment]
sorry war mein fehler geht ! gute arbeit ! super support

**Comment by lordkane** [comment]
hab die datei kopiert und den html code rüber ins share verzeichnis sehe garnix aufem map

**Comment by Mictronics** [comment]
Bitte prüfen ob:
* der Service dump1090-fa läuft `sudo service dump1090-fa status`
* `/run/dump1090-fa` erzeugt wird, Dateien enthält (besonders aircraft.json, stats.json und receiver.json) und diese Dateien nicht leer sind
* die Datei aircraft.json vom Browser direkt aufrufbar ist z.B.: http://192.168.178.25/dump1090/data/aircraft.json (IP oder Hostname anpassen)
* das im Browser kein Fehler erzeugt wird, siehe Javascript Konsole. In Chrome z.B. mit F12 aufrufen und oben Console auswählen.

**Comment by lordkane** [comment]
data ordner findet der nicht :(

**Comment by lordkane** [comment]
root@DietPi:/usr/share/dump1090-fa/html/data# service dump1090-fa status
● dump1090-fa.service - dump1090 ADS-B receiver (FlightAware customization)
   Loaded: loaded (/lib/systemd/system/dump1090-fa.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2019-04-23 16:14:06 BST; 2s ago
     Docs: https://flightaware.com/adsb/piaware/
  Process: 1745 ExecStart=/usr/bin/dump1090-fa $RECEIVER_OPTIONS $DECODER_OPTIONS $NET_OPTIONS $JSON_OPTIONS $PIAWARE_DUMP1090_LOCATION_OPTIONS --write-json /run/dump1090-fa --quiet (code=exited, s
tatus=64)
 Main PID: 1745 (code=exited, status=64)

Apr 23 16:14:06 DietPi systemd[1]: dump1090-fa.service: Unit entered failed state.

**Comment by lordkane** [comment]
hast du email ? das du mal per teamviewer guckst? bin wohl zu doof sorry

**Comment by Mictronics** [comment]
Solved.
