### ISSUE TITLE
Support for Pi HAT GNS 5894

### ISSUE THREAD

**Issue by adsbxchange** [Mictronics/dump1090#15]
GNS Pi Hat setup creates a serial device at /dev/ttyAMA0

Output is raw avr.

https://www.gns-electronics.com/

If you are interested in adding support - I can see if they will send you a hat.

Email me james at adsbexchange.com

**Comment by Mictronics** [comment]
Shouldn't be a big deal since I integrated support for Mode-S Beast already. That is using /dev/ttyAMA0 as well but with different protocol.

**Comment by adsbxchange** [comment]
The format is somewhat awkward.

There's a discussion here:

https://www.adsbexchange.com/forum/threads/new-receiver-from-gns.625451/


Email me and I'll get them to get you hardware.

**Comment by Bill2002** [comment]
Hello Microtronics,

please send me your contact data. I will send you an ADS-B Hat for free ....so you can test easily 
and of course feed....  If you have any question shoot me an PM/email

Thanks 

Bill2002

If you are near Aachen come and visit us for a coffee :-)

**Comment by adsbxchange** [comment]
I emailed to you guys.

**Comment by Mictronics** [comment]
Done with ac3e126.
