### ISSUE TITLE
No web site view on Firefox 54.0 (64bit) in Arch linux

### ISSUE THREAD

**Issue by meijin007** [Mictronics/dump1090#3]
On my Archlinux rasberrypi the website isn't loading. only the 
'ICAO24 address
Registration
ICAO Type
Description
Interesting
Military'
on the left side.
on my mobile device everything is working ok.

also, the default lighttpd.conf index-file.name is pointing to gmap.html which isn't exist.

**Comment by Mictronics** [comment]
My dump1090 fork has nowhere a reference to gmap.html. A wild guess is that you had installed dump1090-mutability before? Now trying my fork?
Change the lighttpd.conf and point the document root to /usr/share/dump1090-fa/html
index file is index.html

**Comment by meijin007** [comment]
Thanks, was my bad.

בתאריך 21 ביוני 2017 12:02,‏ "Mictronics" <notifications@github.com> כתב:
