### ISSUE TITLE
Building Debian package failed on Raspbian Jessie

### ISSUE THREAD

**Issue by Blog404DE** [Mictronics/dump1090#5]
Hi,

i’ve tried to build your dump1090-fa fork and got some problems creating the Debian package on a Raspberry Pi (3) with Raspbian Jessie Lite (current firmware / kernel 4.9.39-v7+) and bladeRF is compiled and installed (as described in your README.md)

```bash
gcc -D_FORTIFY_SOURCE=2 -DSC16Q11_TABLE_BITS=8 -DMODES_DUMP1090_VERSION=\"3.4.0\" -DMODES_DUMP1090_VARIANT=\"dump1090-fa\" -D_GNU_SOURCE -DHTMLPATH=\"/usr/share/dump1090-fa/html\" -DENABLE_RTLSDR -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -std=c11 -O2 -g -W -D_DEFAULT_SOURCE -Wall -Wpadded -Werror -I/usr/include/ -I/usr/include/libusb-1.0  -c dump1090.c -o dump1090.o
<command-line>:0:20: error: expected ‘,’ or ‘;’ before numeric constant
dump1090.c:59:23: note: in definition of macro ‘_stringize’
 #define _stringize(x) x
                       ^
dump1090.c:75:34: note: in expansion of macro ‘verstring’
            "SC16Q11_TABLE_BITS=" verstring(SC16Q11_TABLE_BITS)
                                  ^
dump1090.c:75:44: note: in expansion of macro ‘SC16Q11_TABLE_BITS’
            "SC16Q11_TABLE_BITS=" verstring(SC16Q11_TABLE_BITS)
                                            ^
```

The problem had something todo with "-DSC16Q11_TABLE_BITS=8“. I’ve tried to compile it manually: one time with and without -DSC16Q11_TABLE_BITS=8 as compiler flag and with this flag, the same problem occurred. 

The complete build log: [build.txt](https://github.com/Mictronics/dump1090/files/1183645/build.txt)

**Comment by Mictronics** [comment]
Thanks for pointing this out. I usually do not build packages so missed this completely. But for some reason it worked by normal make.
Pull the latest update for a fix.

**Comment by Blog404DE** [comment]
@Mictronics thx - your new commit fixed the dpkg-buildpackage 👍 

Are there any plans to port the modifications to the new dump1080-fa skyview-gui?

**Comment by Mictronics** [comment]
I'm not going to port the GUI to Skyview. In my opinion there is to much space wasted and no focus on the main purpose, the map and aircraft list. Especially on mobile device or small screens that is a problem.

**Comment by Blog404DE** [comment]
good decision - i didn’t like the new web-gui, too … the waste space for the menubar etc. 👍
