### ISSUE TITLE
Problem fetching data from dump1090

### ISSUE THREAD

**Issue by Geptun** [Mictronics/dump1090#6]
Hi there, I'm unable to get the localhost web end of the flight tracking to recieve any information from your fork of dump1090.

i've tried restarting lighttpd, restarting dump, nothing works. i have the config copied from the dump install directory to the lighttpd directory.

i use the Qupzilla browser on arch linux, any tips on getting it to work?

**Comment by Mictronics** [comment]
Have you copied the data from my fork over a previous installation of dump1090 or dump1090-fa?

Can you access: http://[your_adsbreceiver_host]/dump1090/data/aircraft.json ?

Document root for lighttpd is : /usr/share/dump1090-fa/html

Make sure /etc/lighttpd/conf-available contains the files:

88-dump1090-fa-statcache.conf
89-dump1090-fa.conf

and /etc/lighttpd/conf-enabled contains symlinks to both files.

You may also try to remove any previous installation of dump1090, then build the package of my fork and install that.

**Comment by Geptun** [comment]
I first installed your fork, cause it seemed the best choice out of the 3 forks on the AUR, i didnt notice i needed to copy the lighttpd config from dump tho, lol. 

i then tried thedump1090-fa fork and copied the config when i seen the message in my terminal, that didnt work. so i went back to your fork and copied the config from it, lol.

i have the rtl-sdr, im assuming i put that in the url to test it?

and im not seeing those 2 files or the directory, it ends at /etc/lighttpd with just the single config. 

https://paste.ee/p/e0jq1

**Comment by Mictronics** [comment]
Your lighttpd config is missing the following:

`# Add CORS header`
`server.modules += ( "mod_setenv" )`
`$HTTP["url"] =~ "^/dump1090-fa/data/.*\.json$" {
  setenv.add-response-header = ( "Access-Control-Allow-Origin" => "*" )
}`
`# Add compression for JSON`
`compress.filetype += ( "application/json" )`

Also, if not yet done, you need to check and correct your folder names. Not to mix up dump1090 and dump1090-fa.

**Comment by Mictronics** [comment]
Config that my lighttpd is running with (output from `lighttpd -p -f /etc/lighttpd/lighttpd.conf`).
https://paste.ee/p/FZVyz

**Comment by Geptun** [comment]
i have the correct folders as set by the package maintainer that configured it for the AUR, lol. i'd have to change the folder name and then edit the lighttpd config, lol.

i'll add in the cors header bit, then test it

**Comment by Geptun** [comment]
nope, still no luck
