### ISSUE TITLE
aircraft data missing in aircraft.json file

### ISSUE THREAD

**Issue by LamaBleu** [Mictronics/dump1090#7]
Hi,
First thank you and congrats for porting dump1090 to adalm-pluto. It works on the platform ! And sorry to rise an issue !
I compiled (even cross-compiled) both git-master and 3.6 versions and facing the same issue regarding the content of aircraft.json file. Non-blocking issue.

Dump1090 is receiving messages, on the console , text-mode or raw-mode, no problem .. Using view1090 tool I'm also able to display aircraft list and position ( btw --interactive not working). 
See screenshot.  --net parameter and network stuff working.
However the map appears correctly but empty of planes, and the dashbord doesn't reports any details **except** the version and received messages rate (updated in real-time).
Stopping dump1090, I get the usual AJAX error, so I'm working in the right directory... and I took care to use --write-json parameters when running dump1090.

On the data directory I can find aircraft.json, history_xx.json files updated at regular time but with a very small size. Aircraft.json contains only the time, received messages number, and sometimes ICAO-reg - followed by "version=0".
I customized the config.js with my location, can change layers, etc, no problem ..  I can't see any other strange behaviour displaying the map, except the missing planes ^^
As browser I'm running Vivaldi and Firefox (checked the about:config parameter for firefox) but I don't think it's the issue.
The only error I can see using the browser  "inspector" is the the missing file "upintheair.json".
Can this missing file be the issue ? BTW I don't use FA (no account).
Don't wan't to take your time, just in case you have an idea. Thanks and regards.

Aircraft.json examples:

`{ "now" : 1540223961.3,
  "messages" : 3509,
  "aircraft" : [
  ]
}`

increasing --write-json-every value ...

`{ "now" : 1540221698.0,
  "messages" : 1007,
  "aircraft" : [
    {"hex":"5110d4","version":0,"mlat":[],"tisb":[],"messages":3,"seen":54613.3,"rssi":-49.1},
    {"hex":"020017","version":0,"mlat":[],"tisb":[],"messages":4,"seen":54613.4,"rssi":-43.9}
  ]
}
`

History_xx.json example (noticed here only planes from the same "second"/seen are reported) : 

`{ "now" : 1540223965.4,
  "messages" : 3746,
  "aircraft" : [
    {"hex":"3c66a5","version":0,"mlat":[],"tisb":[],"messages":5,"seen":54613.3,"rssi":-47.1},
    {"hex":"502cc8","version":0,"mlat":[],"tisb":[],"messages":5,"seen":54613.6,"rssi":-45.7},
    {"hex":"4cab9d","version":0,"mlat":[],"tisb":[],"messages":3,"seen":54613.8,"rssi":-45.2},
    {"hex":"3451d9","version":2,"sil_type":"perhour","mlat":[],"tisb":[],"messages":12,"seen":54613.4,"rssi":-40.9},
    {"hex":"34538e","version":2,"sil_type":"perhour","mlat":[],"tisb":[],"messages":14,"seen":54613.3,"rssi":-43.2},
    {"hex":"3cc7fe","version":0,"mlat":[],"tisb":[],"messages":5,"seen":54613.5,"rssi":-47.2}
  ]
}
`

![fa-pluto](https://user-images.githubusercontent.com/26578895/47303965-a2e74680-d625-11e8-854f-6c4872505da3.png)

**Comment by Mictronics** [comment]
Your are first to report such issue. Never seen that behavior.
I assume you run dump1090 only with adalm-pluto as receiver? Did you try a simple RTL-SDR?
When you say cross-compile, you mean to run directly on adalm-pluto? On what other platforms you compiled the source?
From your excellent description I would exclude a web-interface problem. Looks like a json generation or data sourcing one.
However, I have no idea how to reproduce this for debugging.

**Comment by LamaBleu** [comment]
Hi Michael, thank you for your answer.
Yes, I first cross-compiled dump1090 to be run directly on the adalm-pluto. Have to say I'm used to compile tools/firmware for pluto. 
Discovering the issue, I compiled your fork to be run on my computer (for troubleshooting) and got exactly the same problem. 
Will try to compile on another computer or add RTLSDR support as you suggested.
However last evening I was able to populate aicraft.json with valid data, by commenting lines in net_io.c beginning by :  ` if (trackDataValid...`
I don't have explanation and will restart from scratch later.
Let's close this issue, problem is on my side, and I'll add a note once sorted. Thanks a lot !

**Comment by Mictronics** [comment]
Please keep me informed about the outcome. 

trackDataValid (in track.h) can be broken down in two possible reasons not populating json: either source is not valid or data is expired.
SOURCE_INVALID is set only in track.c -> updatePosition()
```
#ifdef DEBUG_CPR_CHECKS
            fprintf(stderr, "global CPR failure (invalid) for (%06X).\n", a->addr);
#endif
            // Global CPR failed because the position produced implausible results.
            // This is bad data. Discard both odd and even messages and wait for a fresh pair.
            // Also disable aircraft-relative positions until we have a new good position (but don't discard the
            // recorded position itself)
            Modes.stats_current.cpr_global_bad++;
            a->cpr_odd_valid.source = a->cpr_even_valid.source = a->position_valid.source = SOURCE_INVALID;
```
You can compile with additional checks and see whether it's a source or expiration problem.
